package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

py_library(
    name = "common",
    srcs = ["common.py"],
    srcs_version = "PY3",
    deps = [
        # attr dep1,
        # numpy dep1,
        # tensorflow dep1,
    ],
)
